<a href="https://colab.research.google.com/github/renato-avellar/ETL-VENDAS-DESAFIO-3-DPT/blob/main/modelagem_star_schema.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import duckdb
import os
import pandas as pd

# 1. Verificação de Arquivos Necessários
arquivos_necessarios = ['modelagem_vendas.sql', 'electronics_sales_silver.csv']
faltando = [f for f in arquivos_necessarios if not os.path.exists(f)]

if faltando:
    print(f"❌ ERRO: Faltam os arquivos: {faltando}")
    print("Por favor, faça o upload deles na barra lateral do Colab.")
else:
    print("✅ Todos os arquivos encontrados. Pronto para iniciar!")

✅ Todos os arquivos encontrados. Pronto para iniciar!

In [13]:
# 2. Configuração do Banco de Dados
DB_NAME = 'vendas_analitico.db'

con = duckdb.connect(DB_NAME)

In [14]:
with open('modelagem_vendas.sql', 'r', encoding='utf-8') as f:
  sql_script = f.read()

con.execute(sql_script)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [15]:
display(con.execute("SHOW TABLES").df())

               name
0    Dim_Calendario
1       Dim_Cliente
2  Dim_Config_Venda
3       Dim_Produto
4      Dim_Vendedor
5       Fato_Vendas

In [17]:
query = """
SELECT
    p.category,
    p.brand,
    SUM(f.net_revenue) as receita_liquida,
    SUM(f.gross_profit) as lucro_bruto
FROM Fato_Vendas f
JOIN Dim_Produto p ON f.product_id = p.product_id
GROUP BY ALL
ORDER BY lucro_bruto DESC
LIMIT 10
"""

display(con.execute(query).df())

      category     brand  receita_liquida   lucro_bruto
0  Electronics     Apple     3.711810e+09  4.674435e+08
1  Electronics   Samsung     1.825759e+09  2.655066e+08
2  Electronics    Lenovo     1.371929e+09  1.523450e+08
3  Electronics    Xiaomi     8.165668e+08  1.106567e+08
4  Electronics      Dell     1.010997e+09  7.589918e+07
5  Electronics     Razer     1.601998e+08  7.416010e+07
6  Electronics      Sony     2.672852e+08  6.450055e+07
7  Electronics  Logitech     1.375160e+08  6.197430e+07
8  Electronics       Jbl     1.855961e+08  4.476222e+07
9  Electronics        Hp     9.582240e+07  4.400074e+07

In [18]:
con.close()